### ISSUE TITLE
Support multiple components and microgrids

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-client-reporting-python#19]
### What's needed?

In the initial version only a combination of one metric, component and microgrid ID each can be requested. The API supports arbitrary lists of microgrid-component IDs and metric IDs. This  functionality should be exposed.

In a first step, multiple metrics for a single component is implemented in https://github.com/frequenz-floss/frequenz-client-reporting-python/pull/26. Multiple components will be addressed separately.

### Proposed solution

The case of multiple metrics, components has been considered in the current design already and only needs to be exposed. First steps in this direction are addressed for multiple metrics in https://github.com/frequenz-floss/frequenz-client-reporting-python/pull/26.

### Additional context

The API requests the cross-combination of the elements in the list of `microgrid_components` and the elements in the list of `metrics`, which might not provide sufficient control over the combinations (e.g. too many or non-existing). For instance
```
metrics = [SOC, power]
microgrid_components = [ {MID, CID_meter}, {MID, CID_battery} ]
```
leads to 4 combinations.

_EDIT: For now we focus on exposing the signature as close to the underlying  API as possible and keep the following as potential future enhancements:_

Alternatively we could require the user to provide request data in the format
```
[[mid1, cid1, metric1], [mid2, cid2, metric2], ...]
```
and potentially have multiple requests whose output needs to be merged.

**Comment by cwasicki** [comment]
Updated scope of this PR since multiple metrics are now addressed here: https://github.com/frequenz-floss/frequenz-client-reporting-python/pull/26.

**Comment by cwasicki** [comment]
Updated issue description narrowing down the scope.

**Comment by flora-hofmann-frequenz** [comment]
Closing issue after merging PR #39.
