### ISSUE TITLE
Support for resampling option

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-client-reporting-python#22]
### What's needed?

The resampling should be exposed if it is supported by the service.

While the client should support any resolution, it needs to be decided whether the service supports these too. If the service only supports a pre-defined set of resolutions, the client has to be extended with resampling capabilities. 

In this case, exposing the service resampling and the client implementation can be done in two iterations.

### Additional context

https://github.com/frequenz-floss/frequenz-api-reporting/issues/19

**Comment by flora-hofmann-frequenz** [comment]
PR #52 merged, thus close this issue.
