### ISSUE TITLE
Support real-time streaming requests

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-client-reporting-python#23]
### What's needed?

The client should support streaming requests in addition to the existing support for historical data.

**Comment by flora-hofmann-frequenz** [comment]
Streaming endpoint is used for historical data from [Release v0.6.0](https://github.com/frequenz-floss/frequenz-client-reporting-python/releases/tag/v0.6.0)

**Comment by cwasicki** [comment]
Fixed by #116.
