### ISSUE TITLE
Support request include option for states

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-client-reporting-python#25]
### What's needed?

The include option for states should be exposed, state data should be converted from the response and integrated with the output data structure.

### Additional context

For output data type see also requirements from: https://github.com/frequenz-floss/frequenz-client-reporting-python/issues/20.

**Comment by flora-hofmann-frequenz** [comment]
Further discussion in https://github.com/frequenz-floss/frequenz-client-common-python/issues/29
