### ISSUE TITLE
Discussion: Remove method to retrieve data for single component

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-client-reporting-python#34]
The current method supports requests for data only for a single component. This is reflected in the name of the method, which is not a simple mapping of the gRPC function that is called. 

In future, the client will support data from multiple components in a single request (see https://github.com/frequenz-floss/frequenz-client-reporting-python/issues/19). For that a function `list_microgrid_components_data` will be implemented that maps to the gRPC function that it calls.

The existing function could then be kept, removed or integrated into the new function.

See comment: https://github.com/frequenz-floss/frequenz-client-reporting-python/pull/16/files#r1554004758

**Comment by llucax** [comment]
Any reason not to put discussions in https://github.com/frequenz-floss/frequenz-client-reporting-python/discussions? You can even easily convert them:

![image](https://github.com/frequenz-floss/frequenz-client-reporting-python/assets/1031485/21c2e4fe-9d5a-44df-8e78-77836e3b55bd)
