### ISSUE TITLE
Rename resolution to resampling_period

### ISSUE THREAD

**Issue by flora-hofmann-frequenz** [frequenz-floss/frequenz-client-reporting-python#79]
### What's needed?

Change resolution to sampling_period for easier understanding what the resolution parameter does.

### Proposed solution

resolution: int to sampling_period: timedelta

**Comment by flora-hofmann-frequenz** [comment]
Should we still make this change @cwasicki? If so I could tackle it next week.

**Comment by cwasicki** [comment]
Yes, to me this makes sense.

**Comment by flora-hofmann-frequenz** [comment]
In my first shot at this, I assume that we only want to change the client to be able to handle `timedelta`, not `PBResamplingOptions(resolution=...)`
